object Versions {
    const val CORE_KTX_VERSION = "1.7.0"
    const val LIFECYCLE_RUNTIME_VERSION = "2.6.0-alpha01"
    const val LIFECYCLE_COMPOSE_VERSION = "2.6.0-alpha01"
    const val ACTIVITY_COMPOSE_VERSION = "1.6.1"
    const val COMPOSE_UI_VERSION = "1.2.0"
    const val COMPOSE_MATERIAL_VERSION = "1.3.0"
    const val COMPOSE_NAVIGATION_VERSION = "2.5.2"
    const val JUNT_VERSION = "4.13.2"
    const val TEST_JUNIT_VERSION = "1.1.3"
    const val ESPRESSO_VERSION = "3.4.0"
    const val RETROFIT_VERSION = "2.9.0"
    const val KOIN_CORE_VERSION = "3.1.5"
    const val KOIN_ANDROID_VERSION = "3.2.0"
    const val COROUTINES_ANDROID_VERSION = "1.6.4"
    const val COROUTINES_CORE_VERSION = "1.5.0"
    const val COIL_VERSION = "2.2.2"
    const val OKHTTP_VERSION = "4.10.0"
}